### ISSUE TITLE
Installing app error

### ISSUE THREAD

**Issue by chrisdent** [f-9t9it/pos_bahrain#493]
```
An error occurred while installing pos_bahrain: Item Barcode: Field Barcode in row 1 cannot be hidden and mandatory without default
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 416, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 296, in install_app
    add_to_installed_apps(name)
  File "apps/frappe/frappe/installer.py", line 324, in add_to_installed_apps
    post_install(rebuild_website)
  File "apps/frappe/frappe/installer.py", line 477, in post_install
    init_singles()
  File "apps/frappe/frappe/installer.py", line 501, in init_singles
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1082, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/pos_bahrain/pos_bahrain/pos_bahrain/doctype/pos_bahrain_settings/pos_bahrain_settings.py", line 22, in on_update
    make_property_setter(
  File "apps/frappe/frappe/custom/doctype/property_setter/property_setter.py", line 64, in make_property_setter
    property_setter.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1082, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/custom/doctype/property_setter/property_setter.py", line 38, in on_update
    validate_fields_for_doctype(self.doc_type)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1037, in validate_fields_for_doctype
    validate_fields(meta)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1458, in validate_fields
    check_hidden_and_mandatory(meta.get("name"), d)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1131, in check_hidden_and_mandatory
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 526, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 494, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 443, in _raise_exception
    raise raise_exception(msg)
frappe.core.doctype.doctype.doctype.HiddenAndMandatoryWithoutDefaultError: Item Barcode: Field Barcode in row 1 cannot be hidden and mandatory without default

```

ERPNext: v14.27.9
Frappe Framework: v14.40.0
Pos Bahrain: v0.4.4

**Comment by chrisdent** [comment]
Update: 

Enable Show Barcode Field in Stock Transactions in Stock Settings
